language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script:
  - mysql -u travis -e 'CREATE DATABASE IF NOT EXISTS travis;'
  - lsb_release -a
  - uname -a
  - env

script: phpunit FF_PDO_TESTS FF_PDO_TESTS.class.php

notifications:
  email: false
