language: php

before_script:
  - composer self-update
  - composer --version
  - composer install --no-interaction --prefer-dist --dev

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

script: vendor/bin/phpunit FF_PDO_TESTS FF_PDO_TESTS.class.php

notifications:
  email: false